### PR TITLE
Update to latest internal version

### PR DESCRIPTION
**Pull request by shantuo**
- Use C++11 integral types.
- Use std::string directly in perf_data_converter / quipper.

### CODE REVIEW

**Comment by s-kanev** [comment]
Looks like the CI run failed:
[build-and-test](https://github.com/google/perf_data_converter/actions/runs/4601969642/jobs/8130434097)
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002

We should upgrade the CI to ubuntu 22.04 before merging, these refactors that look innocent can often cause upstream issues where the toolchain is different.

**Comment by shantuo** [comment]
Ok, some progress, let me upgrade the gcc as well...

**Comment by shantuo** [comment]
The errors look strange, let me try building locally.

**Comment by shantuo** [comment]
Ok, it's green now, PTAL.

**Review by s-kanev — APPROVED** [review]

**Pull request merged**
